import { Rubik } from "next/font/google";

import "../styles/globals.css";

const fontRubik = Rubik({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-rubik",
});

export const metadata = {
  title: "Rumah Belajar Abi Sakinah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fontRubik.variable} antialiased`}>{children}</body>
    </html>
  );
}
